name: Build Android APK

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Folder Structure
      run: ls -R

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK to Telegram
      run: |
        curl -F document=@app/build/outputs/apk/debug/app-debug.apk \
        -F chat_id=7949211631 \
        -F caption="📱 GoProGallery Debug APK\n✅ Auto-built from GitHub Actions" \
        https://api.telegram.org/bot7949211631:AAFYwtrBXeVnKEvE1P3jtwp5FUAyF0sYNDI/sendDocument